/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/rockets/components/rocketCard': RouteRecordInfo<'/rockets/components/rocketCard', '/rockets/components/rocketCard', Record<never, never>, Record<never, never>>,
    '/rockets/containers/': RouteRecordInfo<'/rockets/containers/', '/rockets/containers', Record<never, never>, Record<never, never>>,
    '/rockets/containers/create': RouteRecordInfo<'/rockets/containers/create', '/rockets/containers/create', Record<never, never>, Record<never, never>>,
    '/rockets/containers/detail': RouteRecordInfo<'/rockets/containers/detail', '/rockets/containers/detail', Record<never, never>, Record<never, never>>,
  }
}
